bot_id = 1249465314538950747

[authentication]
# Token to authenticate with Discord.
discord_token = ""

lastfm_key = ""
lastfm_secret = ""
lastfm_redirect_uri = "https://api.botfm.chewawi.gay/lastfm_callback"

# Api information.
[api]
port = 1313
host = "api.botfm.chewawi.gay"

# Database information.
[database]
host = ""
username = ""
password = ""
database = ""
port = 0

[prefix]
# When the bot joins a new guild, this will be the default prefix.
default = "."
# When working with a dev instance, set this to the prefix "override" value for that instance
# to prevent triggering the production instance and the development instance at the same time.
development = "~"

[logging_webhooks]
panic = { token = "", id = 0 }
error = { token = "", id = 0 }
enable_webhooks = true

[dev]
# These Discord user IDs have full control of the bot, including developer-only commands.
developers = []
