[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
toml = "0.8.8"
lazy_static = "1.4.0"

[lints]
workspace = true
