[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
database = { workspace = true }
lastfm = { workspace = true }
serde = { workspace = true }

actix-web = "4.11.0"
actix-files = "0.6"
tera = "1.20.0"

reqwest = "0.12.15"
