[package]
name = "botfm"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"

api = { workspace = true }

common = { workspace = true }
database = { workspace = true }
anyhow = { workspace = true }

tokio = { workspace = true }
reqwest = { workspace = true }

poise = "0.6.1"
sysinfo = "0.33.1"
humanize-bytes = "1.0.6"
actix-web = "4.9.0"
